#!/bin/sh

PATH="/Applications/CMake.app/Contents/bin":"$PATH"
cd "${0%/*}"

./InstallCommandLineTools
./copyFiles

cd SFGUI-0.3.1/
cmake CMakeLists.txt
sudo make install

cd ../
cmake CMakeLists.txt
sudo make install